### ISSUE TITLE
fly doesn't work on latest macOS

### ISSUE THREAD

**Issue by xulike666** [stkevintan/lovewallpaper#1]
message: Unexpected token export
stack:
  - ~/git-clone-repo/lovewallpaper/flyfile.js:27
  - export default async function() {
  - ^^^^^^
  - SyntaxError: Unexpected token export
  -     at Object.exports.runInThisContext (vm.js 73:16)
  -     at Module._compile (module.js 543:28)
  -     at Object.Module._extensions..js (module.js 580:10)
  -     at Module.load (module.js 488:32)
  -     at tryModuleLoad (module.js 447:12)
  -     at Function.Module._load (module.js 439:3)
  -     at require (internal/module.js 20:19)
  -     at Object.module.exports [as spawn] (/usr/local/lib/node_modules/fly/lib/cli/spawn.js 26:9)
  -     at module.exports.next (<anonymous>)
  -     at onFulfilled (/usr/local/lib/node_modules/fly/node_modules/co/index.js 65:19)

**Comment by stkevintan** [comment]
It's the bug of Electron Packager
