### ISSUE TITLE
fly doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by xulike666** [stkevintan/lovewallpaper#2]
message: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
stack: 
  - SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
  -     at exports.runInThisContext (vm.js 53:16)
  -     at Module._compile (module.js 374:25)
  -     at Object.Module._extensions..js (module.js 417:10)
  -     at Module.load (module.js 344:32)
  -     at Function.Module._load (module.js 301:12)
  -     at Module.require (module.js 354:17)
  -     at require (internal/module.js 12:17)
  -     at Object.module.exports [as spawn] (/usr/local/lib/node_modules/fly/lib/cli/spawn.js 26:9)
  -     at next (native)
  -     at onFulfilled (/usr/local/lib/node_modules/fly/node_modules/co/index.js 65:19)

**Comment by stkevintan** [comment]
Please downgrade your `fly` edition to 1.4.1 and `fly-esnext` to 1.0.1
